package CalcApp;


/**
* CalcApp/CalcOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Calc.idl
* Sunday, 19 March 2023 22:41:14 o'clock CET
*/

public interface CalcOperations 
{
  float sum (float a, float b);
  float div (float a, float b) throws CalcApp.CalcPackage.DivisionByZero;
  float mul (float a, float b);
  float sub (float a, float b);
  double square (double a);
  double cube (double a);
  double power (double base, double exponent);
  double sin (double a);
  double cos (double a);
  double tan (double a);
  double log (double a);
  double ln (double a);
  double sqrt (double a);
} // interface CalcOperations
